In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [3]:
# y=2x

# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
# 모델 선언 및 초기화.
# 하나의 입력 x에 대해서 하나의 출력 y를 갖음
# input_dim = 1 / output_dim = 1
model1 = nn.Linear(1, 1)

print(list(model1.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [9]:
optimizer = optim.SGD(model1.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model1(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

C:\Users\intube\dev\pytorch\.venv\Lib\site-packages\torch\autograd\graph.py:979: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


Epoch    0/2000 Cost: 18.562185
Epoch  100/2000 Cost: 0.128051
Epoch  200/2000 Cost: 0.079128
Epoch  300/2000 Cost: 0.048896
Epoch  400/2000 Cost: 0.030215
Epoch  500/2000 Cost: 0.018671
Epoch  600/2000 Cost: 0.011538
Epoch  700/2000 Cost: 0.007129
Epoch  800/2000 Cost: 0.004406
Epoch  900/2000 Cost: 0.002722
Epoch 1000/2000 Cost: 0.001682
Epoch 1100/2000 Cost: 0.001040
Epoch 1200/2000 Cost: 0.000642
Epoch 1300/2000 Cost: 0.000397
Epoch 1400/2000 Cost: 0.000245
Epoch 1500/2000 Cost: 0.000152
Epoch 1600/2000 Cost: 0.000094
Epoch 1700/2000 Cost: 0.000058
Epoch 1800/2000 Cost: 0.000036
Epoch 1900/2000 Cost: 0.000022
Epoch 2000/2000 Cost: 0.000014


In [10]:
# 임의의 입력 4 선언
new_var = torch.FloatTensor([[4.0]])
pred_y = model1(new_var)
print(pred_y)

tensor([[7.9926]], grad_fn=<AddmmBackward0>)


In [11]:
print(list(model1.parameters()))

[Parameter containing:
tensor([[1.9957]], requires_grad=True), Parameter containing:
tensor([0.0097], requires_grad=True)]


In [2]:
# H(x) = w1x1 + w2x2 + w3x3 + b
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [3]:
# 모델 선언
model2 = nn.Linear(3, 1)
print(list(model2.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [4]:
optimizer = optim.SGD(model2.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):

    # H(x)
    prediction = model2(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

C:\Users\intube\dev\pytorch\.venv\Lib\site-packages\torch\autograd\graph.py:979: UserWarning: cudaGetDeviceCount() returned cudaErrorNotSupported, likely using older driver or on CPU machine (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\c10\cuda\CUDAFunctions.cpp:88.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


Epoch    0/2000 Cost: 31667.599609
Epoch  100/2000 Cost: 0.225990
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221936
Epoch  400/2000 Cost: 0.220061
Epoch  500/2000 Cost: 0.218266
Epoch  600/2000 Cost: 0.216570
Epoch  700/2000 Cost: 0.214960
Epoch  800/2000 Cost: 0.213418
Epoch  900/2000 Cost: 0.211951
Epoch 1000/2000 Cost: 0.210563
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207971
Epoch 1300/2000 Cost: 0.206766
Epoch 1400/2000 Cost: 0.205620
Epoch 1500/2000 Cost: 0.204526
Epoch 1600/2000 Cost: 0.203483
Epoch 1700/2000 Cost: 0.202487
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [5]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
pred_y = model2(new_var)
print(pred_y)

tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [6]:
print(list(model2.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [7]:
# 모델 클래스로 구현하기
model = nn.Linear(1, 1)

In [8]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model3 = LinearRegressionModel()

In [ ]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

model4 = MultivariateLinearRegressionModel()