In [1]:
import numpy as np

### 1D with Numpy

In [2]:
t = np.array([0, 1, 2, 3, 4, 5, 6])

print(t)

[0 1 2 3 4 5 6]


In [5]:
print("Rank of t:", t.ndim) # 차원
print("Shape of t:", t.shape) # 크기

Rank of t: 1
Shape of t: (7,)


In [9]:
# 원소 접근 - 슬라이싱
print('t[0]:', t[0])
print('t[1]:', t[1])
print('t[2]:', t[2])
print('t[-1]:', t[-1])
print("")

print('t[:2]:', t[:2])
print('t[3:]:', t[3:])
print("")

print('t[::2]:', t[::2])

t[0]: 0
t[1]: 1
t[2]: 2
t[-1]: 6

t[:2]: [0 1]
t[3:]: [3 4 5 6]

t[::2]: [0 2 4 6]


### 2D with Numpy

In [11]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)
