In [2]:
import torch
import numpy as np

### 1D with Pytorch

In [5]:
t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim()) # 차원
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [7]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D with Pytorch

In [9]:
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [12]:
print(t[:, 1]) # 첫 번째 차원을 전체 선택한 상황에서 두 번째 차원의 첫 번째 것만 가져옴
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [13]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### BroadCasting
1) 자동으로 크기를 맞춰 연산을 수행하게 만드는 기능

In [15]:
m1 = torch.FloatTensor([[3, 2]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 4.]])


In [17]:
# 행렬 + 스칼라
m1 = torch.FloatTensor([[3, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[6., 5.]])


In [20]:
# 벡터 + 벡터
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1)
print(m2)
print(m1 + m2)

tensor([[1., 2.]])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


### 자주 사용되는 기능들

In [25]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(m1)
print(m2)
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [27]:
# Element-wise 곱셈(브로드캐스팅)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [31]:
# 평균
t = torch.FloatTensor([1, 2])
print(t.mean())
print("---")

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print("---")

# dim=0 => 첫 번째 차원==행
# 열 방향으로 평균을 내라
print(t.mean(dim=0))

tensor(1.5000)
---
tensor(2.5000)
---
tensor([2., 3.])


In [33]:
# 덧셈
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print("---")

print(t.sum())
print(t.sum(dim=0))

tensor([[1., 2.],
        [3., 4.]])
---
tensor(10.)
tensor([4., 6.])


In [36]:
# 최대(Max)와 아그맥스(ArgMax)
# 아그맥스는 최댓값을 가진 인덱스를 리턴
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max())
print(t.max(dim=0))
print("---")

print("Max: ", t.max(dim=0)[0])
print("Argmax: ", t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
---
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [42]:
# 뷰(View)
# 원소의 수를 유지하면서 텐서의 크기를 변경
# Numpy의 reshape 역할
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)
print("---")

print("3차원 텐서에서 2차원 텐서로 변경")
print(ft.view([-1, 3]))
# -1: 첫 번째 차원은 잘 모르겠으니, 파이토치에 맡기겠다.
# 3: 두 번째 차원의 길이는 3을 갖게 해달라.
print(ft.view([-1, 3]).shape)
print("---")

print("3차원 텐서의 크기 변경")
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])
---
3차원 텐서에서 2차원 텐서로 변경
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
3차원 텐서의 크기 변경
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [8]:
# 스퀴즈(Squeeze)
# 1인 차원을 제거
ft1 = torch.FloatTensor([[0], [1], [2]])
print(ft1)
print(ft1.shape)
print("---")

print("Squeeze")
print(ft1.squeeze())
print(ft1.squeeze().shape)
print("---")

# 언스퀴즈(Unsqueeze)
# 특정 위치에 1인 차원을 추가
print("Unsqueeze")
ft2 = torch.Tensor([0, 1, 2])
print(ft2)
print(ft2.shape)
print(ft2.unsqueeze(0))
print(ft2.unsqueeze(0).shape)
print(ft2.unsqueeze(1))
print(ft2.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
---
Squeeze
tensor([0., 1., 2.])
torch.Size([3])
---
Unsqueeze
tensor([0., 1., 2.])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [12]:
# Type Casting
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [14]:
# Concatenate
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [16]:
# Stacking
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [19]:
# ones_like, zeros_like
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [22]:
# In-place Operation
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.0))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
